BIN	:=	Principale_2013

SRCS	:=	src/Principale_2013.c  \
            src/Prop2Moteurs.c \
            src/i2c_m.c \
            src/WMP.c

## Information concernant le compilateur
include ../commun.mk
## À modifier si le fichier est utilisé sur un autre pc

