BIN	:=	TestCodeur

SRCS	:=	src/Poivron2010.c  \
            src/serie.c        \
            src/Odometrie.c


## Information concernant le compilateur
include ../commun.mk
## À modifier si le fichier est utilisé sur un autre pc

