BIN	:=	Moteur_2013

SRCS	:=	src/Moteur_2013.c  \
            src/serie.c      \
            src/M_prop.c     \
            src/Odometrie.c


## Information concernant le compilateur
include ../commun.mk
## À modifier si le fichier est utilisé sur un autre pc

